# Generated by Django 4.0.6 on 2022-07-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
